const actionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UNSET_CURRENT_USER: 'UNSET_CURRENT_USER',
  GET_COMMENT: 'GET_COMMENT',
  CREATE_COMMENT: 'CREATE_COMMENT',
  CREAT_REPLY: 'CREAT_REPLY',
  DELETE_COMMENT: 'DELETE_COMMENT',
};
export default actionTypes;
