const actionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UNSET_CURRENT_USER: 'UNSET_CURRENT_USER',
  GET_COMMENT: 'GET_COMMENT',
  CREATE_COMMENT: 'CREATE_COMMENT',
  CREAT_REPLY: 'CREAT_REPLY',
  DELETE_COMMENT: 'DELETE_COMMENT',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
  GET_USER_ARTICLES_SUCCESS: 'GET_USER_ARTICLE_SUCCESS',
  GET_USER_ARTICLES_FAILURE: 'GET_USER_ARTICLE_FAILURE',
};
export default actionTypes;
