export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_ERROR = 'CREATE_ARTICLE_ERROR';
export const CREATE_ARTICLE_LOADING = 'CREATE_ARTICLE_LOADING';
export const GET_ALL_TAGS = 'GET_ALL_TAGS';
