export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const CLEAR_CURRENT_ARTICLE = 'CLEAR_CURRENT_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
